# Projeto de Support Vector Machines 

Bem vindo a seu projet de Support Vector Machine Project! Basta seguir o notebook e as instruções abaixo. Vamos analisar o famoso conjunto de dados da íris!

## Os dados
Para esta série de palestras, estaremos usando o famoso [conjunto de dados de íris](http://en.wikipedia.org/wiki/Iris_flower_data_set).

O conjunto de dados florais Iris ou o conjunto de dados Iris de Fisher é um conjunto de dados multivariados introduzido por Sir Ronald Fisher em 1936 como um exemplo de análise discriminante.

O conjunto de dados é composto por 50 amostras de cada uma das três espécies de íris (Iris setosa, Iris virginica e Iris versicolor), de modo que 150 amostras totais. Foram medidas quatro características de cada amostra: o comprimento e a largura das sépalas e pétalas, em centimetros.

Aqui está uma imagem dos três diferentes tipos de íris:

Bem-vindo ao seu Projeto de Máquina de Vetores de Suporte! Basta seguir o caderno e as instruções abaixo. Vamos analisar o famoso conjunto de dados da íris!

In [ ]:
# Uma iris setosa
from IPython.display import Image
url = 'http://upload.wikimedia.org/wikipedia/commons/5/56/Kosaciec_szczecinkowaty_Iris_setosa.jpg'
Image(url,width=300, height=300)

In [ ]:
# Uma iris versicolor
from IPython.display import Image
url = 'http://upload.wikimedia.org/wikipedia/commons/4/41/Iris_versicolor_3.jpg'
Image(url,width=300, height=300)

In [ ]:
# Uma iris virginica
from IPython.display import Image
url = 'http://upload.wikimedia.org/wikipedia/commons/9/9f/Iris_virginica.jpg'
Image(url,width=300, height=300)

O conjunto de dados da íris contém medidas de 150 flores da íris de três espécies diferentes.

As três classes no conjunto de dados Iris:

     Iris-setosa (n = 50)
     Iris-versicolor (n = 50)
     Iris-virginica (n = 50)

Os quatro recursos do conjunto de dados Iris:

     comprimento sepal em cm
     Largura sepal em cm
     comprimento da pétala em cm
     largura da pétala em cm

## Obter os dados

** Use seaborn para obter os dados da íris usando: iris = sns.load_dataset('iris') **

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

iris = sns.load_dataset('iris')

Vamos visualizar os dados e iniciá-lo!

## Análise de dados exploratórios

Tempo para colocar seu conhecimento de dados à prova! Tente recriar os seguintes gráficos, certifique-se de importar as bibliotecas que você precisa!

** Importe algumas bibliotecas que você acha que você precisará. **

In [ ]:
sns.pairplot(iris)

** Crie um parplot do conjunto de dados. Qual espécie de flor parece ser a mais separável? **

In [ ]:
sns.pairplot(iris, hue='species')

** Crie um kde de comprimento sepal versus largura sepal para espécies de flores setosa. **

In [ ]:
setosa = iris[iris['species'] == 'setosa']

sns.kdeplot(x='sepal_width', y='sepal_length', data=setosa, cmap='plasma', shade=True, shade_lowest=False)

# Divisao treino-teste

** Divida seus dados em um conjunto de treinamento e um conjunto de testes. **

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = iris.drop('species',inplace=False, axis=1)
y = iris['species']

# Treino um modelo

Agora é hora de treinar um classificador de SVM.

** Chame o modelo SVC() da sklearn e ajuste o modelo aos dados de treinamento. **

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## Avaliação do modelo

** Agora obtenha previsões do modelo e crie uma matriz de confusão e um relatório de classificação. **

[[15  0  0]
 [ 0 13  1]
 [ 0  0 16]]


             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        15
 versicolor       1.00      0.93      0.96        14
  virginica       0.94      1.00      0.97        16

avg / total       0.98      0.98      0.98        45



Uau! Você deveria ter notado que seu modelo foi muito bom! Vejamos se podemos ajustar os parâmetros para tentar melhorar ainda mais (improvável, e você provavelmente ficaria satisfeito com esses resultados em termos reais, porque o conjunto de dados é bastante pequeno, mas eu apenas quero que você pratique o uso do GridSearch.

## Prática do Gridsearch 

** Importe GridsearchCV do SciKit Learn.**

** Crie um dicionário chamado param_grid e preencha alguns parâmetros para C e gama. **

** Crie um objeto GridSearchCV e ajuste-o aos dados de treinamento. **

Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] gamma=1, C=0.1 ..................................................
[CV] ......................................... gamma=1, C=0.1 -   0.0s
[CV] gamma=1, C=0.1 ..................................................
[CV] ......................................... gamma=1, C=0.1 -   0.0s
[CV] gamma=1, C=0.1 ..................................................
[CV] ......................................... gamma=1, C=0.1 -   0.0s
[CV] gamma=0.1, C=0.1 ................................................
[CV] ....................................... gamma=0.1, C=0.1 -   0.0s
[CV] gamma=0.1, C=0.1 ................................................
[CV] ....................................... gamma=0.1, C=0.1 -   0.0s
[CV] gamma=0.1, C=0.1 ................................................
[CV] ....................................... gamma=0.1, C=0.1 -   0.0s
[CV] gamma=0.01, C=0.1 ...............................................
[CV] ...........

[Parallel(n_jobs=1)]: Done  40 tasks       | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  48 out of  48 | elapsed:    0.2s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'gamma': [1, 0.1, 0.01, 0.001], 'C': [0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=2)

** Agora pegue esse modelo de Grid e crie algumas previsões usando o conjunto de teste e crie relatórios de classificação e matrizes de confusão para eles. Você conseguiu melhorar algo? **

[[15  0  0]
 [ 0 13  1]
 [ 0  0 16]]


             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        15
 versicolor       1.00      0.93      0.96        14
  virginica       0.94      1.00      0.97        16

avg / total       0.98      0.98      0.98        45



Você deveria ter conseguido praticamente o mesmo ou exatamente o mesmo, isso faz sentido, basicamente há apenas um ponto que é muito confuso para separar, o que faz sentido, não queremos ter um modelo de superposição que possa trabalhar com isso.